name: ir_built_values_schema
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-86.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  built_value: ^8.7.0
  built_collection: ^5.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  built_value_generator: ^8.9.2
  build_runner: '>=1.0.0 <3.0.0'
